### ISSUE TITLE
cloudfront_distribution_origin_access_identity_enabled query fails due SQL error

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-mod-terraform-aws-compliance#77]
**Describe the bug**

CloudFront distributions should have origin access identity enabled
cannot extract elements from an object (SQLSTATE 22023)

**Steampipe version (`steampipe -v`)**
Example: v0.3.0

**Plugin version (`steampipe plugin list`)**
Example: v0.5.0

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

**Expected behavior**

**Additional context**

**Comment by misraved** [comment]
Addressed in https://github.com/turbot/steampipe-mod-terraform-aws-compliance/pull/80
