### ISSUE TITLE
should there be a control to check ingress on security groups as well as 

### ISSUE THREAD

**Issue by judell** [turbot/steampipe-mod-terraform-aws-compliance#85]
we have `vpc_network_acl_allow_ssh_port_22_ingress` but when scanning this example code (from https://spacelift.io/blog/iac-scanning) there was no complaint

```
resource "aws_security_group" "example_sg" {
  name        = "public_sg"
  description = "public security group"
  vpc_id      = aws_vpc.example_vpc.id
  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}
```

**Comment by cbruno10** [comment]
If helpful, when adapting these queries for VPC security group rules, the ingress rules in network ACLs can be found in `ingress ->> 'cidr_block'`, while in security groups they're found in `ingress ->> 'cidr_blocks'`
